name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -w lint
      - run: pnpm -w build
      - run: pnpm -w test
      - run: pnpm bundle-check
      - run: pnpm sbom
