name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w lint
      - run: pnpm -w build
      - run: pnpm -w test
      - run: pnpm -w check:bundles
      - run: pnpm -w check:a11y || true
      - run: pnpm -w security:sbom
      - run: pnpm -w security:provenance
